// This file was automatically generated by Database.makeDatabaseVariables() on 2008/10/5 16:42:14
namespace CommonTools.Database
{
    public static class Net7
    {
        public enum Tables { assets, buffs, effects, faction_matrix, factions, item_ammo, 
                             item_ammo_type, item_base, item_beam, item_device, item_effect_base, 
                             item_effect_container, item_effect_stats, item_effects, item_engine, item_manufacture, 
                             item_manufacturer_base, item_missile, item_other_req, item_projectile, item_reactor, 
                             item_refine, item_shield, item_type, level_xp, manufacturers, 
                             missions, mob_base, mob_items, mob_spawn_group, sector_nav_points, 
                             sector_objects, sector_objects_harvestable, sector_objects_harvestable_restypes, sector_objects_mob, sector_objects_planets, 
                             sector_objects_starbases, sector_objects_stargates, sectors, skill_abilities, skill_levels, 
                             skills, starbase_npc_avatar_templates, starbase_npcs, starbase_rooms, starbase_terminals, 
                             starbase_vender_groups, starbase_vender_inventory, starbase_vendors, starbases, systems, 
                             table_changes, versions };

        public enum Table_assets { [ColName("base_id")] [DataType("int")] _base_id,
                                   [ColName("descr")] [DataType("text")] _descr,
                                   [ColName("main_cat")] [DataType("text")] _main_cat,
                                   [ColName("sub_cat")] [DataType("text")] _sub_cat,
                                   [ColName("filename")] [DataType("text")] _filename,
                                   [ColName("rslid")] [DataType("int")] _rslid };

        public enum Table_buffs { [ColName("buff_id")] [DataType("bigint")] _buff_id,
                                  [ColName("buff_name")] [DataType("varchar")] _buff_name,
                                  [ColName("StatName")] [DataType("varchar")] _StatName,
                                  [ColName("StatType")] [DataType("int")] _StatType,
                                  [ColName("EffectID")] [DataType("int")] _EffectID,
                                  [ColName("tooltip")] [DataType("text")] _tooltip,
                                  [ColName("description")] [DataType("text")] _description,
                                  [ColName("is_good_buff")] [DataType("tinyint")] _is_good_buff };

        public enum Table_effects { [ColName("effect_id")] [DataType("bigint")] _effect_id,
                                    [ColName("effect_class")] [DataType("text")] _effect_class,
                                    [ColName("description")] [DataType("text")] _description,
                                    [ColName("start_link_id")] [DataType("bigint")] _start_link_id,
                                    [ColName("next_link_id")] [DataType("bigint")] _next_link_id,
                                    [ColName("base_asset_id")] [DataType("bigint")] _base_asset_id,
                                    [ColName("sound_fx_file")] [DataType("text")] _sound_fx_file };

        public enum Table_factions { [ColName("faction_id")] [DataType("bigint")] _faction_id,
                                     [ColName("name")] [DataType("varchar")] _name,
                                     [ColName("description")] [DataType("text")] _description };

        public enum Table_faction_matrix { [ColName("id")] [DataType("bigint")] _id,
                                           [ColName("faction_id")] [DataType("bigint")] _faction_id,
                                           [ColName("faction_entry_id")] [DataType("bigint")] _faction_entry_id,
                                           [ColName("base_value")] [DataType("int")] _base_value,
                                           [ColName("current_value")] [DataType("int")] _current_value };

        public enum Table_item_ammo { [ColName("item_id")] [DataType("int")] _item_id,
                                      [ColName("ammo_type_id")] [DataType("int")] _ammo_type_id,
                                      [ColName("damage_type")] [DataType("tinyint")] _damage_type,
                                      [ColName("fire_effect")] [DataType("int")] _fire_effect,
                                      [ColName("maneuv_100")] [DataType("float unsigned")] _maneuv_100,
                                      [ColName("damage_100")] [DataType("float unsigned")] _damage_100,
                                      [ColName("range_100")] [DataType("float unsigned")] _range_100 };

        public enum Table_item_ammo_type { [ColName("id")] [DataType("int")] _id,
                                           [ColName("sub_category")] [DataType("smallint")] _sub_category,
                                           [ColName("name")] [DataType("varchar")] _name };

        public enum Table_item_base { [ColName("id")] [DataType("int")] _id,
                                      [ColName("level")] [DataType("tinyint")] _level,
                                      [ColName("category")] [DataType("smallint")] _category,
                                      [ColName("sub_category")] [DataType("smallint")] _sub_category,
                                      [ColName("type")] [DataType("tinyint")] _type,
                                      [ColName("price")] [DataType("int")] _price,
                                      [ColName("max_stack")] [DataType("smallint")] _max_stack,
                                      [ColName("name")] [DataType("varchar")] _name,
                                      [ColName("description")] [DataType("text")] _description,
                                      [ColName("manufacturer")] [DataType("int")] _manufacturer,
                                      [ColName("2d_asset")] [DataType("int")] _2d_asset,
                                      [ColName("3d_asset")] [DataType("int")] _3d_asset,
                                      [ColName("no_trade")] [DataType("tinyint")] _no_trade,
                                      [ColName("no_store")] [DataType("tinyint")] _no_store,
                                      [ColName("no_destroy")] [DataType("tinyint")] _no_destroy,
                                      [ColName("no_manu")] [DataType("tinyint")] _no_manu,
                                      [ColName("unique")] [DataType("tinyint")] _unique,
                                      [ColName("item_base_id")] [DataType("int")] _item_base_id,
                                      [ColName("custom_flag")] [DataType("tinyint")] _custom_flag,
                                      [ColName("status")] [DataType("tinyint")] _status,
                                      [ColName("effect_id")] [DataType("bigint")] _effect_id };

        public enum Table_item_beam { [ColName("item_id")] [DataType("int")] _item_id,
                                      [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                      [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                      [ColName("damage_type")] [DataType("tinyint")] _damage_type,
                                      [ColName("fire_effect")] [DataType("smallint")] _fire_effect,
                                      [ColName("damage_100")] [DataType("float unsigned")] _damage_100,
                                      [ColName("range_100")] [DataType("float unsigned")] _range_100,
                                      [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                      [ColName("reload_100")] [DataType("float unsigned")] _reload_100 };

        public enum Table_item_device { [ColName("item_id")] [DataType("int")] _item_id,
                                        [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                        [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                        [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                        [ColName("range_100")] [DataType("smallint")] _range_100 };

        public enum Table_item_effects { [ColName("ItemEffectID")] [DataType("int")] _ItemEffectID,
                                         [ColName("ItemID")] [DataType("int")] _ItemID,
                                         [ColName("item_effect_base_id")] [DataType("int")] _item_effect_base_id,
                                         [ColName("Var1Data")] [DataType("float")] _Var1Data,
                                         [ColName("Var2Data")] [DataType("float")] _Var2Data,
                                         [ColName("Var3Data")] [DataType("float")] _Var3Data };

        public enum Table_item_effect_base { [ColName("EffectID")] [DataType("int")] _EffectID,
                                             [ColName("EffectType")] [DataType("int")] _EffectType,
                                             [ColName("Name")] [DataType("varchar")] _Name,
                                             [ColName("Description")] [DataType("varchar")] _Description,
                                             [ColName("Tooltip")] [DataType("varchar")] _Tooltip,
                                             [ColName("flag1")] [DataType("int")] _flag1,
                                             [ColName("flag2")] [DataType("int")] _flag2,
                                             [ColName("Constant1Value")] [DataType("float")] _Constant1Value,
                                             [ColName("Constant1Stat")] [DataType("varchar")] _Constant1Stat,
                                             [ColName("Constant1Type")] [DataType("int")] _Constant1Type,
                                             [ColName("Constant2Value")] [DataType("float")] _Constant2Value,
                                             [ColName("Constant2Stat")] [DataType("varchar")] _Constant2Stat,
                                             [ColName("Constant2Type")] [DataType("int")] _Constant2Type,
                                             [ColName("Var1Stat")] [DataType("varchar")] _Var1Stat,
                                             [ColName("Var1Type")] [DataType("int")] _Var1Type,
                                             [ColName("Var2Stat")] [DataType("varchar")] _Var2Stat,
                                             [ColName("Var2Type")] [DataType("int")] _Var2Type,
                                             [ColName("Var3Stat")] [DataType("varchar")] _Var3Stat,
                                             [ColName("Var3Type")] [DataType("int")] _Var3Type,
                                             [ColName("Buff_Name")] [DataType("varchar")] _Buff_Name };

        public enum Table_item_effect_container { [ColName("EffectContainerID")] [DataType("int")] _EffectContainerID,
                                                  [ColName("ItemID")] [DataType("int")] _ItemID,
                                                  [ColName("EquipEffect")] [DataType("int")] _EquipEffect,
                                                  [ColName("RechargeTime")] [DataType("int")] _RechargeTime,
                                                  [ColName("Unknown2")] [DataType("int")] _Unknown2,
                                                  [ColName("_Range")] [DataType("int")] __Range,
                                                  [ColName("Unknown4")] [DataType("int")] _Unknown4 };

        public enum Table_item_effect_stats { [ColName("Stat_Name")] [DataType("varchar")] _Stat_Name,
                                              [ColName("Stat_Description")] [DataType("varchar")] _Stat_Description };

        public enum Table_item_engine { [ColName("item_id")] [DataType("int")] _item_id,
                                        [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                        [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                        [ColName("warp")] [DataType("smallint")] _warp,
                                        [ColName("warp_drain_100")] [DataType("float unsigned")] _warp_drain_100,
                                        [ColName("thrust_100")] [DataType("smallint")] _thrust_100,
                                        [ColName("signature_100")] [DataType("smallint")] _signature_100,
                                        [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                        [ColName("range_100")] [DataType("smallint")] _range_100 };

        public enum Table_item_manufacture { [ColName("item_id")] [DataType("int")] _item_id,
                                             [ColName("comp_1")] [DataType("int")] _comp_1,
                                             [ColName("comp_2")] [DataType("int")] _comp_2,
                                             [ColName("comp_3")] [DataType("int")] _comp_3,
                                             [ColName("comp_4")] [DataType("int")] _comp_4,
                                             [ColName("comp_5")] [DataType("int")] _comp_5,
                                             [ColName("comp_6")] [DataType("int")] _comp_6,
                                             [ColName("difficulty")] [DataType("int")] _difficulty };

        public enum Table_item_manufacturer_base { [ColName("id")] [DataType("int")] _id,
                                                   [ColName("name")] [DataType("varchar")] _name };

        public enum Table_item_missile { [ColName("item_id")] [DataType("int")] _item_id,
                                         [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                         [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                         [ColName("ammo")] [DataType("varchar")] _ammo,
                                         [ColName("ammo_per_shot")] [DataType("tinyint")] _ammo_per_shot,
                                         [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                         [ColName("reload_100")] [DataType("float unsigned")] _reload_100,
                                         [ColName("ammo_type_id")] [DataType("int")] _ammo_type_id };

        public enum Table_item_other_req { [ColName("item_id")] [DataType("int")] _item_id,
                                           [ColName("overall_lvl")] [DataType("smallint")] _overall_lvl,
                                           [ColName("combat_lvl")] [DataType("smallint")] _combat_lvl,
                                           [ColName("explore_lvl")] [DataType("smallint")] _explore_lvl,
                                           [ColName("trade_level")] [DataType("smallint")] _trade_level,
                                           [ColName("other_skill")] [DataType("varchar")] _other_skill,
                                           [ColName("over_skill_lvl")] [DataType("tinyint")] _over_skill_lvl,
                                           [ColName("energy_drain")] [DataType("float unsigned")] _energy_drain,
                                           [ColName("shield_drain")] [DataType("float unsigned")] _shield_drain };

        public enum Table_item_projectile { [ColName("item_id")] [DataType("int")] _item_id,
                                            [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                            [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                            [ColName("ammo")] [DataType("varchar")] _ammo,
                                            [ColName("ammo_per_shot")] [DataType("tinyint")] _ammo_per_shot,
                                            [ColName("range_100")] [DataType("float unsigned")] _range_100,
                                            [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                            [ColName("reload_100")] [DataType("float unsigned")] _reload_100,
                                            [ColName("ammo_type_id")] [DataType("int")] _ammo_type_id };

        public enum Table_item_reactor { [ColName("item_id")] [DataType("int")] _item_id,
                                         [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                         [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                         [ColName("cap_100")] [DataType("int")] _cap_100,
                                         [ColName("recharge_100")] [DataType("float unsigned")] _recharge_100,
                                         [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                         [ColName("range_100")] [DataType("smallint")] _range_100 };

        public enum Table_item_refine { [ColName("item_id")] [DataType("int")] _item_id,
                                        [ColName("refine_id")] [DataType("int")] _refine_id };

        public enum Table_item_shield { [ColName("item_id")] [DataType("int")] _item_id,
                                        [ColName("rest_prof")] [DataType("tinyint")] _rest_prof,
                                        [ColName("rest_race")] [DataType("tinyint")] _rest_race,
                                        [ColName("cap_100")] [DataType("int")] _cap_100,
                                        [ColName("recharge_100")] [DataType("float unsigned")] _recharge_100,
                                        [ColName("energy_100")] [DataType("float unsigned")] _energy_100,
                                        [ColName("range_100")] [DataType("smallint")] _range_100 };

        public enum Table_item_type { [ColName("id")] [DataType("int")] _id,
                                      [ColName("name")] [DataType("varchar")] _name };

        public enum Table_level_xp { [ColName("level")] [DataType("bigint")] _level,
                                     [ColName("trade_xp")] [DataType("bigint")] _trade_xp,
                                     [ColName("explore_xp")] [DataType("bigint")] _explore_xp,
                                     [ColName("combat_xp")] [DataType("bigint")] _combat_xp };

        public enum Table_manufacturers { [ColName("manufacturer_id")] [DataType("bigint")] _manufacturer_id,
                                          [ColName("name")] [DataType("varchar")] _name,
                                          [ColName("slogan")] [DataType("text")] _slogan,
                                          [ColName("faction_id")] [DataType("bigint")] _faction_id };

        public enum Table_missions { [ColName("mission_id")] [DataType("int")] _mission_id,
                                     [ColName("mission_XML")] [DataType("text")] _mission_XML,
                                     [ColName("mission_name")] [DataType("text")] _mission_name,
                                     [ColName("mission_key")] [DataType("int")] _mission_key,
                                     [ColName("mission_type")] [DataType("smallint")] _mission_type };

        public enum Table_mob_base { [ColName("mob_id")] [DataType("bigint")] _mob_id,
                                     [ColName("name")] [DataType("text")] _name,
                                     [ColName("level")] [DataType("int")] _level,
                                     [ColName("intelligence")] [DataType("float")] _intelligence,
                                     [ColName("bravery")] [DataType("float")] _bravery,
                                     [ColName("type")] [DataType("int")] _type,
                                     [ColName("faction_id")] [DataType("bigint")] _faction_id,
                                     [ColName("base_asset_id")] [DataType("bigint")] _base_asset_id,
                                     [ColName("altruism")] [DataType("float")] _altruism,
                                     [ColName("aggressiveness")] [DataType("float")] _aggressiveness,
                                     [ColName("ai")] [DataType("text")] _ai,
                                     [ColName("h")] [DataType("float")] _h,
                                     [ColName("s")] [DataType("float")] _s,
                                     [ColName("v")] [DataType("float")] _v,
                                     [ColName("scale")] [DataType("float")] _scale };

        public enum Table_mob_items { [ColName("id")] [DataType("bigint")] _id,
                                      [ColName("mob_id")] [DataType("bigint")] _mob_id,
                                      [ColName("item_base_id")] [DataType("bigint")] _item_base_id,
                                      [ColName("usage_chance")] [DataType("int")] _usage_chance,
                                      [ColName("drop_chance")] [DataType("int")] _drop_chance,
                                      [ColName("type")] [DataType("int")] _type,
                                      [ColName("qty")] [DataType("int")] _qty };

        public enum Table_mob_spawn_group { [ColName("id")] [DataType("bigint")] _id,
                                            [ColName("spawn_group_id")] [DataType("bigint")] _spawn_group_id,
                                            [ColName("mob_id")] [DataType("bigint")] _mob_id,
                                            [ColName("group_index")] [DataType("bigint")] _group_index };

        public enum Table_sectors { [ColName("sector_id")] [DataType("bigint")] _sector_id,
                                    [ColName("name")] [DataType("text")] _name,
                                    [ColName("x_min")] [DataType("float")] _x_min,
                                    [ColName("y_min")] [DataType("float")] _y_min,
                                    [ColName("z_min")] [DataType("float")] _z_min,
                                    [ColName("x_max")] [DataType("float")] _x_max,
                                    [ColName("y_max")] [DataType("float")] _y_max,
                                    [ColName("z_max")] [DataType("float")] _z_max,
                                    [ColName("grid_x")] [DataType("int")] _grid_x,
                                    [ColName("grid_y")] [DataType("int")] _grid_y,
                                    [ColName("grid_z")] [DataType("int")] _grid_z,
                                    [ColName("fog_near")] [DataType("float")] _fog_near,
                                    [ColName("fog_far")] [DataType("float")] _fog_far,
                                    [ColName("debris_mode")] [DataType("int")] _debris_mode,
                                    [ColName("light_backdrop")] [DataType("tinyint")] _light_backdrop,
                                    [ColName("fog_backdrop")] [DataType("tinyint")] _fog_backdrop,
                                    [ColName("swap_backdrop")] [DataType("tinyint")] _swap_backdrop,
                                    [ColName("backdrop_fog_near")] [DataType("float")] _backdrop_fog_near,
                                    [ColName("backdrop_fog_far")] [DataType("float")] _backdrop_fog_far,
                                    [ColName("max_tilt")] [DataType("float")] _max_tilt,
                                    [ColName("auto_level")] [DataType("tinyint")] _auto_level,
                                    [ColName("impulse_rate")] [DataType("float")] _impulse_rate,
                                    [ColName("decay_velocity")] [DataType("float")] _decay_velocity,
                                    [ColName("decay_spin")] [DataType("float")] _decay_spin,
                                    [ColName("backdrop_asset")] [DataType("int")] _backdrop_asset,
                                    [ColName("greetings")] [DataType("text")] _greetings,
                                    [ColName("notes")] [DataType("text")] _notes,
                                    [ColName("system_id")] [DataType("int")] _system_id,
                                    [ColName("galaxy_x")] [DataType("float")] _galaxy_x,
                                    [ColName("galaxy_y")] [DataType("float")] _galaxy_y,
                                    [ColName("sector_ip_addr")] [DataType("bigint")] _sector_ip_addr,
                                    [ColName("galaxy_z")] [DataType("float")] _galaxy_z,
                                    [ColName("sector_type")] [DataType("int")] _sector_type };

        public enum Table_sector_nav_points { [ColName("sector_object_id")] [DataType("bigint")] _sector_object_id,
                                              [ColName("nav_type")] [DataType("int")] _nav_type,
                                              [ColName("signature")] [DataType("float")] _signature,
                                              [ColName("is_huge")] [DataType("tinyint")] _is_huge,
                                              [ColName("sector_id")] [DataType("bigint")] _sector_id,
                                              [ColName("base_xp")] [DataType("int")] _base_xp,
                                              [ColName("exploration_range")] [DataType("float")] _exploration_range };

        public enum Table_sector_objects { [ColName("sector_object_id")] [DataType("bigint")] _sector_object_id,
                                           [ColName("base_asset_id")] [DataType("int")] _base_asset_id,
                                           [ColName("h")] [DataType("float")] _h,
                                           [ColName("s")] [DataType("float")] _s,
                                           [ColName("v")] [DataType("float")] _v,
                                           [ColName("type")] [DataType("tinyint")] _type,
                                           [ColName("scale")] [DataType("float")] _scale,
                                           [ColName("position_x")] [DataType("float")] _position_x,
                                           [ColName("position_y")] [DataType("float")] _position_y,
                                           [ColName("position_z")] [DataType("float")] _position_z,
                                           [ColName("orientation_u")] [DataType("float")] _orientation_u,
                                           [ColName("orientation_v")] [DataType("float")] _orientation_v,
                                           [ColName("orientation_w")] [DataType("float")] _orientation_w,
                                           [ColName("orientation_z")] [DataType("float")] _orientation_z,
                                           [ColName("name")] [DataType("text")] _name,
                                           [ColName("appears_in_radar")] [DataType("tinyint")] _appears_in_radar,
                                           [ColName("radar_range")] [DataType("float")] _radar_range,
                                           [ColName("sector_id")] [DataType("bigint")] _sector_id,
                                           [ColName("gate_to")] [DataType("bigint")] _gate_to,
                                           [ColName("sound_effect_id")] [DataType("bigint")] _sound_effect_id,
                                           [ColName("sound_effect_range")] [DataType("float")] _sound_effect_range };

        public enum Table_sector_objects_harvestable { [ColName("resource_id")] [DataType("bigint")] _resource_id,
                                                       [ColName("level")] [DataType("int")] _level,
                                                       [ColName("field")] [DataType("int")] _field,
                                                       [ColName("res_count")] [DataType("int")] _res_count,
                                                       [ColName("spawn_radius")] [DataType("float")] _spawn_radius,
                                                       [ColName("pop_rock_chance")] [DataType("float")] _pop_rock_chance,
                                                       [ColName("max_field_radius")] [DataType("float")] _max_field_radius };

        public enum Table_sector_objects_harvestable_restypes { [ColName("id")] [DataType("bigint")] _id,
                                                                [ColName("group_id")] [DataType("bigint")] _group_id,
                                                                [ColName("type")] [DataType("int")] _type };

        public enum Table_sector_objects_mob { [ColName("mob_id")] [DataType("bigint")] _mob_id,
                                               [ColName("mob_count")] [DataType("int")] _mob_count,
                                               [ColName("mob_spawn_radius")] [DataType("float")] _mob_spawn_radius,
                                               [ColName("respawn_time")] [DataType("float")] _respawn_time,
                                               [ColName("delayed_spawn")] [DataType("tinyint")] _delayed_spawn };

        public enum Table_sector_objects_planets { [ColName("planet_id")] [DataType("bigint")] _planet_id,
                                                   [ColName("orbit_id")] [DataType("int")] _orbit_id,
                                                   [ColName("orbit_dist")] [DataType("float")] _orbit_dist,
                                                   [ColName("orbit_angle")] [DataType("float")] _orbit_angle,
                                                   [ColName("orbit_rate")] [DataType("float")] _orbit_rate,
                                                   [ColName("rotate_angle")] [DataType("float")] _rotate_angle,
                                                   [ColName("rotate_rate")] [DataType("float")] _rotate_rate,
                                                   [ColName("tilt_angle")] [DataType("float")] _tilt_angle,
                                                   [ColName("is_landable")] [DataType("tinyint")] _is_landable };

        public enum Table_sector_objects_starbases { [ColName("starbase_id")] [DataType("bigint")] _starbase_id,
                                                     [ColName("capShip")] [DataType("tinyint")] _capShip,
                                                     [ColName("dockable")] [DataType("tinyint")] _dockable };

        public enum Table_sector_objects_stargates { [ColName("stargate_id")] [DataType("bigint")] _stargate_id,
                                                     [ColName("classSpecific")] [DataType("tinyint")] _classSpecific,
                                                     [ColName("faction_id")] [DataType("bigint")] _faction_id };

        public enum Table_skills { [ColName("skill_id")] [DataType("bigint")] _skill_id,
                                   [ColName("name")] [DataType("text")] _name,
                                   [ColName("description")] [DataType("text")] _description,
                                   [ColName("is_activated")] [DataType("tinyint")] _is_activated,
                                   [ColName("category")] [DataType("text")] _category,
                                   [ColName("warrior_max_level")] [DataType("int")] _warrior_max_level,
                                   [ColName("sentinal_max_level")] [DataType("int")] _sentinal_max_level,
                                   [ColName("privateer_max_level")] [DataType("int")] _privateer_max_level,
                                   [ColName("defender_max_level")] [DataType("int")] _defender_max_level,
                                   [ColName("explorer_max_level")] [DataType("int")] _explorer_max_level,
                                   [ColName("seeker_max_level")] [DataType("int")] _seeker_max_level,
                                   [ColName("enforcer_max_level")] [DataType("int")] _enforcer_max_level,
                                   [ColName("scout_max_level")] [DataType("int")] _scout_max_level,
                                   [ColName("tradesman_max_level")] [DataType("int")] _tradesman_max_level };

        public enum Table_skill_abilities { [ColName("ability_id")] [DataType("bigint")] _ability_id,
                                            [ColName("skill_id")] [DataType("bigint")] _skill_id,
                                            [ColName("min_level")] [DataType("int")] _min_level,
                                            [ColName("description")] [DataType("text")] _description,
                                            [ColName("activation_cost")] [DataType("int")] _activation_cost,
                                            [ColName("name")] [DataType("text")] _name };

        public enum Table_skill_levels { [ColName("skill_level_id")] [DataType("bigint")] _skill_level_id,
                                         [ColName("skill_id")] [DataType("bigint")] _skill_id,
                                         [ColName("level")] [DataType("int")] _level,
                                         [ColName("description")] [DataType("text")] _description };

        public enum Table_starbases { [ColName("starbase_id")] [DataType("bigint")] _starbase_id,
                                      [ColName("sector_id")] [DataType("int")] _sector_id,
                                      [ColName("name")] [DataType("varchar")] _name,
                                      [ColName("type")] [DataType("int")] _type,
                                      [ColName("is_active")] [DataType("int")] _is_active,
                                      [ColName("description")] [DataType("varchar")] _description,
                                      [ColName("welcome_message")] [DataType("varchar")] _welcome_message,
                                      [ColName("target_sector_object")] [DataType("bigint")] _target_sector_object,
                                      [ColName("faction_id")] [DataType("bigint")] _faction_id,
                                      [ColName("starbase_sector_id")] [DataType("bigint")] _starbase_sector_id };

        public enum Table_starbase_npcs { [ColName("npc_Id")] [DataType("bigint")] _npc_Id,
                                          [ColName("first_name")] [DataType("varchar")] _first_name,
                                          [ColName("last_name")] [DataType("varchar")] _last_name,
                                          [ColName("location")] [DataType("int")] _location,
                                          [ColName("faction_id")] [DataType("bigint")] _faction_id,
                                          [ColName("description")] [DataType("varchar")] _description,
                                          [ColName("talk_tree_handle")] [DataType("varchar")] _talk_tree_handle,
                                          [ColName("room_id")] [DataType("bigint")] _room_id,
                                          [ColName("npc_index")] [DataType("int")] _npc_index };

        public enum Table_starbase_npc_avatar_templates { [ColName("avatar_template_id")] [DataType("bigint")] _avatar_template_id,
                                                          [ColName("avatar_type")] [DataType("int")] _avatar_type,
                                                          [ColName("avatar_version")] [DataType("tinyint")] _avatar_version,
                                                          [ColName("race")] [DataType("int")] _race,
                                                          [ColName("profession")] [DataType("int")] _profession,
                                                          [ColName("gender")] [DataType("int")] _gender,
                                                          [ColName("mood_type")] [DataType("int")] _mood_type,
                                                          [ColName("personality")] [DataType("tinyint")] _personality,
                                                          [ColName("nlp")] [DataType("tinyint")] _nlp,
                                                          [ColName("shirt_type")] [DataType("tinyint")] _shirt_type,
                                                          [ColName("pants_type")] [DataType("tinyint")] _pants_type,
                                                          [ColName("head_type")] [DataType("tinyint")] _head_type,
                                                          [ColName("hair_type")] [DataType("tinyint")] _hair_type,
                                                          [ColName("ear_type")] [DataType("tinyint")] _ear_type,
                                                          [ColName("goggle_num")] [DataType("tinyint")] _goggle_num,
                                                          [ColName("beard_num")] [DataType("tinyint")] _beard_num,
                                                          [ColName("weapon_hip_num")] [DataType("tinyint")] _weapon_hip_num,
                                                          [ColName("weapon_unique_num")] [DataType("tinyint")] _weapon_unique_num,
                                                          [ColName("weapon_back_num")] [DataType("tinyint")] _weapon_back_num,
                                                          [ColName("head_texture_num")] [DataType("tinyint")] _head_texture_num,
                                                          [ColName("tatoo_texture_num")] [DataType("tinyint")] _tatoo_texture_num,
                                                          [ColName("tatoo_x")] [DataType("float")] _tatoo_x,
                                                          [ColName("tatoo_y")] [DataType("float")] _tatoo_y,
                                                          [ColName("tatoo_z")] [DataType("float")] _tatoo_z,
                                                          [ColName("hair_color_0")] [DataType("float")] _hair_color_0,
                                                          [ColName("hair_color_1")] [DataType("float")] _hair_color_1,
                                                          [ColName("hair_color_2")] [DataType("float")] _hair_color_2,
                                                          [ColName("beard_color_0")] [DataType("float")] _beard_color_0,
                                                          [ColName("beard_color_1")] [DataType("float")] _beard_color_1,
                                                          [ColName("beard_color_2")] [DataType("float")] _beard_color_2,
                                                          [ColName("eye_color_0")] [DataType("float")] _eye_color_0,
                                                          [ColName("eye_color_1")] [DataType("float")] _eye_color_1,
                                                          [ColName("eye_color_2")] [DataType("float")] _eye_color_2,
                                                          [ColName("skin_color_0")] [DataType("float")] _skin_color_0,
                                                          [ColName("skin_color_1")] [DataType("float")] _skin_color_1,
                                                          [ColName("skin_color_2")] [DataType("float")] _skin_color_2,
                                                          [ColName("shirt1_color_0")] [DataType("float")] _shirt1_color_0,
                                                          [ColName("shirt1_color_1")] [DataType("float")] _shirt1_color_1,
                                                          [ColName("shirt1_color_2")] [DataType("float")] _shirt1_color_2,
                                                          [ColName("shirt2_color_0")] [DataType("float")] _shirt2_color_0,
                                                          [ColName("shirt2_color_1")] [DataType("float")] _shirt2_color_1,
                                                          [ColName("shirt2_color_2")] [DataType("float")] _shirt2_color_2,
                                                          [ColName("pants1_color_0")] [DataType("float")] _pants1_color_0,
                                                          [ColName("pants1_color_1")] [DataType("float")] _pants1_color_1,
                                                          [ColName("pants1_color_2")] [DataType("float")] _pants1_color_2,
                                                          [ColName("pants2_color_0")] [DataType("float")] _pants2_color_0,
                                                          [ColName("pants2_color_1")] [DataType("float")] _pants2_color_1,
                                                          [ColName("pants2_color_2")] [DataType("float")] _pants2_color_2,
                                                          [ColName("shirt1_metal")] [DataType("int")] _shirt1_metal,
                                                          [ColName("shirt2_metal")] [DataType("int")] _shirt2_metal,
                                                          [ColName("pants1_metal")] [DataType("int")] _pants1_metal,
                                                          [ColName("pants2_metal")] [DataType("int")] _pants2_metal,
                                                          [ColName("body_weight0")] [DataType("float")] _body_weight0,
                                                          [ColName("body_weight1")] [DataType("float")] _body_weight1,
                                                          [ColName("body_weight2")] [DataType("float")] _body_weight2,
                                                          [ColName("body_weight3")] [DataType("float")] _body_weight3,
                                                          [ColName("body_weight4")] [DataType("float")] _body_weight4,
                                                          [ColName("head_weight0")] [DataType("float")] _head_weight0,
                                                          [ColName("head_weight1")] [DataType("float")] _head_weight1,
                                                          [ColName("head_weight2")] [DataType("float")] _head_weight2,
                                                          [ColName("head_weight3")] [DataType("float")] _head_weight3,
                                                          [ColName("head_weight4")] [DataType("float")] _head_weight4 };

        public enum Table_starbase_rooms { [ColName("room_id")] [DataType("bigint")] _room_id,
                                           [ColName("type")] [DataType("int")] _type,
                                           [ColName("style")] [DataType("int")] _style,
                                           [ColName("fog_near")] [DataType("int")] _fog_near,
                                           [ColName("fog_far")] [DataType("int")] _fog_far,
                                           [ColName("fog_red")] [DataType("int")] _fog_red,
                                           [ColName("fog_green")] [DataType("int")] _fog_green,
                                           [ColName("fog_blue")] [DataType("int")] _fog_blue,
                                           [ColName("description")] [DataType("varchar")] _description,
                                           [ColName("starbase_id")] [DataType("bigint")] _starbase_id };

        public enum Table_starbase_terminals { [ColName("terminal_id")] [DataType("bigint")] _terminal_id,
                                               [ColName("location")] [DataType("int")] _location,
                                               [ColName("type")] [DataType("int")] _type,
                                               [ColName("attribute")] [DataType("int")] _attribute,
                                               [ColName("description")] [DataType("varchar")] _description,
                                               [ColName("room_id")] [DataType("bigint")] _room_id,
                                               [ColName("terminal_index")] [DataType("int")] _terminal_index };

        public enum Table_starbase_vender_groups { [ColName("GroupID")] [DataType("int")] _GroupID,
                                                   [ColName("GroupName")] [DataType("varchar")] _GroupName,
                                                   [ColName("SellMultiplyer")] [DataType("float")] _SellMultiplyer,
                                                   [ColName("BuyMultiplyer")] [DataType("float")] _BuyMultiplyer,
                                                   [ColName("BuyOnlyList")] [DataType("int")] _BuyOnlyList };

        public enum Table_starbase_vender_inventory { [ColName("id")] [DataType("int")] _id,
                                                      [ColName("groupid")] [DataType("int")] _groupid,
                                                      [ColName("itemid")] [DataType("int")] _itemid,
                                                      [ColName("sell_price")] [DataType("int")] _sell_price,
                                                      [ColName("buy_price")] [DataType("int")] _buy_price,
                                                      [ColName("quanity")] [DataType("int")] _quanity };

        public enum Table_starbase_vendors { [ColName("vendor_id")] [DataType("bigint")] _vendor_id,
                                             [ColName("level")] [DataType("int")] _level,
                                             [ColName("booth_type")] [DataType("int")] _booth_type,
                                             [ColName("groupid")] [DataType("int")] _groupid };

        public enum Table_systems { [ColName("system_id")] [DataType("int")] _system_id,
                                    [ColName("name")] [DataType("text")] _name,
                                    [ColName("galaxy_x")] [DataType("float")] _galaxy_x,
                                    [ColName("galaxy_y")] [DataType("float")] _galaxy_y,
                                    [ColName("galaxy_z")] [DataType("float")] _galaxy_z,
                                    [ColName("color_r")] [DataType("float")] _color_r,
                                    [ColName("color_g")] [DataType("float")] _color_g,
                                    [ColName("color_b")] [DataType("float")] _color_b,
                                    [ColName("notes")] [DataType("text")] _notes };

        public enum Table_table_changes { [ColName("id")] [DataType("int")] _id,
                                          [ColName("tablename")] [DataType("varchar")] _tablename,
                                          [ColName("modification")] [DataType("varchar")] _modification,
                                          [ColName("username")] [DataType("varchar")] _username,
                                          [ColName("modified")] [DataType("varchar")] _modified,
                                          [ColName("new_values")] [DataType("varchar")] _new_values,
                                          [ColName("old_values")] [DataType("varchar")] _old_values };

        public enum Table_versions { [ColName("EName")] [DataType("varchar")] _EName,
                                     [ColName("Version")] [DataType("varchar")] _Version };

        public enum Enum_item_type { _Systems = 0,
                                     _Weapon = 1,
                                     _Shields = 2,
                                     _Sensor = 3,
                                     _Ejector = 4,
                                     _Turret = 5,
                                     _Engine = 6,
                                     _Reactor = 7,
                                     _Controler = 8,
                                     _Robot = 9,
                                     _Ammo = 10,
                                     _Devices = 11,
                                     _System = 12,
                                     _Base = 13,
                                     _Beam_Weapon = 14,
                                     _Missile_Launcher = 15,
                                     _Projectile_Weapon = 16,
                                     _Countermeasure = 17,
                                     _Over_Rides = 18 };

    }
}
